name: avienceclans
version: '1.0'
main: org.avience.avienceclans.Avienceclans
api-version: '1.19'
description: A clan management plugin for Minecraft servers.
author: zeus2
softdepend: [ Geyser-Spigot, Floodgate ]

commands:
  clan:
    description: Manage your clan.
    usage: /<command> <create|delete|invite|kick|promote|demote|info|join|leave>
    permission: avienceClans.clan
  clanchat:
    description: Manage clan chat settings.
    usage: /<command> <toggle|spy>
    aliases: [ cchat, clanmessage ]
    permission: avienceClans.clanchat

permissions:
  avienceClans.reload:
    description: Reloads the plugin
    default: op
  avienceClans.status:
    description: Shows information about all the clans
    default: op
  avienceClans.spy:
    description: Allows user to spy on clanchat messages
    default: op
  avienceClans.clan.create:
    description: Create a new clan
    default: true
  avienceClans.clan.delete:
    description: Delete your clan
    default: true
  avienceClans.clan.invite:
    description: Invite a player to your clan
    default: true
  avienceClans.clan.kick:
    description: Kick a member from your clan
    default: true
  avienceClans.clan.promote:
    description: Promote a member in your clan
    default: true
  avienceClans.clan.demote:
    description: Demote a member in your clan
    default: true
  avienceClans.clan.info:
    description: Show information about a clan
    default: true
  avienceClans.clan.join:
    description: Join a clan you've been invited to
    default: true
  avienceClans.clan.leave:
    description: Leave your current clan
    default: true
  avienceClans.clanchat.toggle:
    description: Toggles clanchat on and off
    default: true
  avienceClans.clanchat.spy:
    description: Toggles clanchat spy on and off
    default: op